### ISSUE TITLE
Discord.py error while deleting all channels,vc , categories

### ISSUE THREAD

**Issue by git-SwitchBlade** [python-discord/bot#1646]
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 26, in on_command_error
    await delete(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 374, in __call__
    return await self.callback(*args, **kwargs)
  File "main.py", line 313, in delete
    await channel.delete() # Delete all channels
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/abc.py", line 574, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/http.py", line 250, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10003): Unknown Channel

**Comment by Xithrius** [comment]
I think you may be in the wrong repository.

This is for the bot within the Python Discord server.
