### ISSUE TITLE
TypeError: function() argument 'code' must be code, not str

### ISSUE THREAD

**Issue by Aayush2005** [python-discord/bot#2300]
I was trying to run the source coded of the Python Bot , I have all the modules installed with correct versions , still it is raising error starting from `bot-main\bot__main__.py", line 3, in <module>
    import aiohttp`

ending with 
`class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str`

**Comment by Aayush2005** [comment]
I tried all of them , none helped ! 
also I reinstalled all the modules required for the execution with the supported versions .

`Traceback (most recent call last):
  File "c:\Users\aayus\Downloads\bot-main\bot\__main__.py", line 3, in <module>
    import aiohttp
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 35, in <module>
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\http.py", line 7, in <module>  
    from .http_parser import (
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
PS C:\Users\aayus> & C:/Users/aayus/AppData/Local/Programs/Python/Python39/python.exe c:/Users/aayus/Downloads/bot-main/bot/__main__.py
Traceback (most recent call last):
  File "c:\Users\aayus\Downloads\bot-main\bot\__main__.py", line 3, in <module>
    import aiohttp
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\http.py", line 7, in <module>  
    from .http_parser import (
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\aayus\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str`

This is the whole traceback

**Comment by MarkKoz** [comment]
Are you using the latest code from the repository? We've fairly recently moved the bot to be on Python 3.10, but it appears you're still using 3.9. If you used Poetry to install the dependencies, as is intended, then it would've warned you about that or even failed I think.

**Comment by wookie184** [comment]
Closing this as I think the question was solved, if you're still having issues it's probably easiest if you ask for help on the server.
