### ISSUE TITLE
Fix IndexError exception when paginator gets called with empty object

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#246]
Calling the paginator with an empty object (e.g., like it is called when you call `!otname list` if there are no names in the list) currently results in an IndexError exception. It's probably a good idea to go over all paginators to check if the all suffer from the same bug.

Either add a check or add an empty line when the input object is empty.

```
Traceback (most recent call last):
  File "/home/sebastiaan/.local/share/virtualenvs/bot-05f_83Kn/src/discord-py/discord/client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "/home/sebastiaan/pydis/bot/bot/cogs/events.py", line 146, in on_command_error
    raise e.original
  File "/home/sebastiaan/.local/share/virtualenvs/bot-05f_83Kn/src/discord-py/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/sebastiaan/pydis/bot/bot/cogs/off_topic_names.py", line 164, in list_command
    await LinePaginator.paginate(lines, ctx, embed, max_size=400, empty=False)
  File "/home/sebastiaan/pydis/bot/bot/pagination.py", line 165, in paginate
    embed.description = paginator.pages[current_page]
IndexError: list index out of range
```

**Comment by SebastiaanZ** [comment]
Should be fixed now with #247
