### ISSUE TITLE
Unhandled exception in snekbox during eval

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#264]
Evaling this code with `!eval` lead to an unhandled exception in snekbox and makes the bot nonreactive for a short period of time:

```py
print(True == 1)
print(False == 0)
print(True == 2)
print(False == 10)
```

The log messages I'm getting in my dev bot are below. **Note: ** The asyncio error/http internal server error may or may not be related, but keep repeating after the eval failed.

```
Jan 09 20:53:49 pd.beardfist.com Bot: |               bot.cogs.snekbox |    ERROR | Unhandled error in snekbox eval: Command raised an exception: AttributeError: 'str' object has no attribute 'ack' ('str' object has no attribute 'ack')
Jan 09 20:54:26 pd.beardfist.com Bot: |                bot.cogs.events |    DEBUG | Command eval has a local error handler, ignoring.
Jan 09 20:55:28 pd.beardfist.com Bot: |                        asyncio |    ERROR | Task exception was never retrieved
future: <Task finished coro=<Message.add_reaction() done, defined at /home/sebastiaan/.local/share/virtualenvs/bot-05f_83Kn/src/discord-py/discord/message.py:650> exception=HTTPException('INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error',)>
Traceback (most recent call last):
  File "/home/sebastiaan/.local/share/virtualenvs/bot-05f_83Kn/src/discord-py/discord/message.py", line 679, in add_reaction
    await self._state.http.add_reaction(self.id, self.channel.id, emoji)
  File "/home/sebastiaan/.local/share/virtualenvs/bot-05f_83Kn/src/discord-py/discord/http.py", line 216, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
```

**Comment by SebastiaanZ** [comment]
Update: All evals are suddenly breaking. The internal server errors are probably a problem with Discord.

**Comment by SebastiaanZ** [comment]
Looks like it was related to the Discord outage. I don't know why, though.

I'm closing this for now.
