### ISSUE TITLE
AntiSpam fails to upload deleted messages if rules are triggered in quick succession due to race condition

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#412]
The AntiSpam occasionally fails to upload messages it deletes to the API. This is caused by an interplay between the way the AntiSpam processes messages and the fact that the API rejects duplicate message IDs (since messages can only be deleted once). 

To explain what's going on, I'll give give an example using the `burst` rule. However, this holds for most (all?) of the rules the AntiSpam cog uses.

---

Let's assume that we have a burst filter with the following settings:
```
        burst:
            interval: 5
            max: 5
```
This means that if a single users sends more than 5 messages (`max`) in a single channel within 5 seconds (`interval`), this rule is triggered and the messages are deleted. 

The way the AntiSpam cog goes about this is by having an `on_message` event listener that, for each message it receives, gathers up all the messages in that channel that fall within the time frame (in this case 5 seconds), checks if those relevant message contain more than 5 messages by the same author, and, if so, it will upload the messages to the API, delete them, and mute the user.

Since it does this for each message that it receives, as soon as the sixth message within five seconds is detected, it will trigger the rule. However, if a **seventh** message is received quickly after the sixth, it's often the case that the first six message **have not been deleted yet** (asynchronous...), but all still fall within the last 5 seconds.

This causes the rule triggered by the seventh message to partially contain the same message IDs as the rule triggered by the first six messages, causing the API to reject the second POST request since it requires unique message IDs:

```
(...) Issuing `self.maybe_delete_messages` with                     [621659499047944203, 621659497735127050, 621659496003141642, 621659494073630731]
(...) Issuing `self.maybe_delete_messages` with [621659500599967746, 621659499047944203, 621659497735127050, 621659496003141642, 621659494073630731]
```
As you can see, the second call contains all the message IDs of the first one, plus one additional message ID, causing the API to be called with non-unique message IDs. (Sebastiaan: Logs trimmed to save space + lists of IDs aligned to make duplicates more obvious)

This leads to a number of Exceptions, this one always happens in bot:

```py
Sep 12 12:21:09 pd.beardfist.com Bot: |                           asyncio |    ERROR | Task exception was never retrieved
future: <Task finished coro=<AntiSpam.punish() done, defined at /home/sebastiaan/pydis/repositories/testbot/bot/cogs/antispam.py:97> exception=ResponseCodeError()>
Traceback (most recent call last):
  File "/home/sebastiaan/pydis/repositories/testbot/bot/cogs/antispam.py", line 110, in punish
    url = await self.mod_log.upload_log(messages, msg.guild.me.id)
  File "/home/sebastiaan/pydis/repositories/testbot/bot/cogs/modlog.py", line 66, in upload_log
    for message in messages
  File "/home/sebastiaan/pydis/repositories/testbot/bot/api.py", line 50, in post
    self.maybe_raise_for_status(resp, raise_for_status)
  File "/home/sebastiaan/pydis/repositories/testbot/bot/api.py", line 36, in maybe_raise_for_status
    raise ResponseCodeError(response=response)
bot.api.ResponseCodeError
```
With the site logs showing a `400` in the logs:
```
web_1       | Bad Request: /bot/deleted-messages
web_1       | "POST /bot/deleted-messages HTTP/1.1" 400 204
```

This means that any request that has a message ID in it that was also part of a previous request will be rejected, and the unique messages it contained that were not part of the previous request **will not be stored** in the database.

**A solution** could be to have the API accept requests with duplicate messages, but filter them out and only store the new ones. Downside is that the messages will be split over multiple deletion contexts and that we'll receive multiple "deleted messages" alerts in #mod-alerts.

---

However, there's a complication. Occasionally, though, the site **also** throws an exception and it returns a `500` and/or `502` (internal server error) after the **database** rejects the messages. This means that they passed the validation stage (otherwise it would have returned a `400`) and only fails when the database fails to store it.

This could mean that we also have a race condition at the API side of things that probably won't be fixed by the solution mentioned above.

So far, I've only seen this happen with a `burst_shared` rule with multiple authors involved, though. I've not been able to reproduce it otherwise. Maybe something else is happening for that rule specifically, but I've not been able to find what.

```py
postgres_1  | 2019-09-12 08:05:59.201 UTC [943] ERROR:  duplicate key value violates unique constraint "api_deletedmessage_pkey"
postgres_1  | 2019-09-12 08:05:59.201 UTC [943] DETAIL:  Key (id)=(621617490845237248) already exists.
postgres_1  | 2019-09-12 08:05:59.201 UTC [943] STATEMENT:  INSERT INTO "api_deletedmessage" ("id", "author_id", "channel_id", "content", "embeds", "deletion_context_id") VALUES (621617490845237248, 532614300519497729, 476196221845897270, '1', '{}'::jsonb[], 18)
web_1       | "POST /bot/deleted-messages HTTP/1.1" 201 502
web_1       | Internal Server Error: /bot/deleted-messages
web_1       | Traceback (most recent call last):
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1       |     return self.cursor.execute(sql, params)
web_1       | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "api_deletedmessage_pkey"
web_1       | DETAIL:  Key (id)=(621617490845237248) already exists.
web_1       | 
web_1       | 
web_1       | The above exception was the direct cause of the following exception:
web_1       | 
web_1       | Traceback (most recent call last):
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1       |     response = get_response(request)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1       |     response = self.process_exception_by_middleware(e, request)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1       |     return view_func(*args, **kwargs)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
web_1       |     return self.dispatch(request, *args, **kwargs)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
web_1       |     response = self.handle_exception(exc)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
web_1       |     self.raise_uncaught_exception(exc)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
web_1       |     response = handler(request, *args, **kwargs)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/rest_framework/mixins.py", line 21, in create
web_1       |     self.perform_create(serializer)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/rest_framework/mixins.py", line 26, in perform_create
web_1       |     serializer.save()
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/rest_framework/serializers.py", line 214, in save
web_1       |     self.instance = self.create(validated_data)
web_1       |   File "/app/pydis_site/apps/api/serializers.py", line 82, in create
web_1       |     **message
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1       |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
web_1       |     obj.save(force_insert=True, using=self.db)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
web_1       |     force_update=force_update, update_fields=update_fields)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
web_1       |     force_update, using, update_fields,
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
web_1       |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
web_1       |     using=using, raw=raw)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1       |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
web_1       |     return query.get_compiler(using=using).execute_sql(return_id)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
web_1       |     cursor.execute(sql, params)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
web_1       |     return super().execute(sql, params)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
web_1       |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
web_1       |     return executor(sql, params, many, context)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1       |     return self.cursor.execute(sql, params)
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
web_1       |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1       |   File "/opt/bitnami/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1       |     return self.cursor.execute(sql, params)
web_1       | django.db.utils.IntegrityError: duplicate key value violates unique constraint "api_deletedmessage_pkey"
web_1       | DETAIL:  Key (id)=(621617490845237248) already exists.
web_1       | 
web_1       | "POST /bot/deleted-messages HTTP/1.1" 500 20176
```

**Comment by lemonsaurus** [comment]
Resolved in 14a6c1.
