### ISSUE TITLE
The reddit cog break at the end of the month.

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#636]
Hi, the last day of the month, the reddit cog return this traceback 
```
Traceback (most recent call last):
  File "...\lib\site-packages\discord\ext\tasks\__init__.py", line 68, in _loop
    await self.coro(*args, **kwargs)
  File "...\bot\bot\cogs\reddit.py", line 133, in auto_poster_loop
    midnight_tomorrow = now.replace(day=now.day + 1, hour=0, minute=0, second=0)
ValueError: day is out of range for month
```
The cog should use a [`datetime.timedelta`](https://docs.python.org/3/library/datetime.html#timedelta-objects) object instead of `.replace`

**Comment by loksonarius** [comment]
Making a quick fix for this now.
