### ISSUE TITLE
Error when antispam attempts to delete messages which have attachments

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#670]
I reproduced this by sending 3 duplicate messages, all containing (the same) attachment. Messages do get deleted if they are sent without the attachments.

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/mark/repos/python/bot-pydis/.venv/lib/python3.7/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "/home/mark/repos/python/bot-pydis/bot/cogs/antispam.py", line 203, in on_message
    await self.maybe_delete_messages(message.channel, relevant_messages)
  File "/home/mark/repos/python/bot-pydis/bot/cogs/antispam.py", line 232, in maybe_delete_messages
    await channel.delete_messages(messages)
  File "/home/mark/repos/python/bot-pydis/.venv/lib/python3.7/site-packages/discord/channel.py", line 287, in delete_messages
    await self._state.http.delete_messages(self.id, message_ids)
  File "/home/mark/repos/python/bot-pydis/.venv/lib/python3.7/site-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
In messages.1: The set already contains this value
```

**Comment by MarkKoz** [comment]
This is actually fixed by #655. It was being caused by a duplicate message being included in the bulk delete list.
