### ISSUE TITLE
ZeroDivisionError in tag fuzzy search

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#787]
Don't know exactly what triggered it cause I noticed it way up in my bot's log history.

```
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/mark/repos/python/bot-pydis/.venv/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/mark/repos/python/bot-pydis/bot/cogs/error_handler.py", line 92, in on_command_error
    await ctx.invoke(tags_get_command, tag_name=ctx.invoked_with)
  File "/home/mark/repos/python/bot-pydis/.venv/lib/python3.7/site-packages/discord/ext/commands/context.py", line 132, in invoke
    ret = await command.callback(*arguments, **kwargs)
  File "/home/mark/repos/python/bot-pydis/bot/cogs/tags.py", line 128, in get_command
    founds = await self._get_tag(tag_name)
  File "/home/mark/repos/python/bot-pydis/bot/cogs/tags.py", line 87, in _get_tag
    return self._get_suggestions(tag_name)
  File "/home/mark/repos/python/bot-pydis/bot/cogs/tags.py", line 66, in _get_suggestions
    for tag_title, tag in self._cache.items()
  File "/home/mark/repos/python/bot-pydis/bot/cogs/tags.py", line 66, in <dictcomp>
    for tag_title, tag in self._cache.items()
  File "/home/mark/repos/python/bot-pydis/bot/cogs/tags.py", line 60, in _fuzzy_search
    return current / len(_search) * 100
ZeroDivisionError: division by zero
```

CC @ikuyarihS

**Comment by F4zii** [comment]
Seems like no match (REGEX_NON_ALPHABET) was found, Is returning (unreachable value?) an option?

**Comment by Numerlor** [comment]
Looks like the error handler tags don't go through `TagNameConverter` which discards invalid tag names, can look at it more if assigned.

**Comment by MarkKoz** [comment]
Sure @Numerlor, I've assigned you.

**Comment by Numerlor** [comment]
This will also get triggered when going through the tag commands, but passing a tag name without any letters. Do we want to allow those or should they also be rejected in the converter?

**Comment by MarkKoz** [comment]
Without letters? As in A-Z? Or do you mean without any characters? Cause I think tag names with, for example, digits only, should be allowed (kind of weird but why not).

**Comment by Numerlor** [comment]
Tag names with only numbers already get rejected
https://github.com/python-discord/bot/blob/1ccc0f11fd4511d13c7cdf59070dca86465fe59f/bot/converters.py#L166-L170
But other ascii characters go through and fail at the alpha regex e.g. ----- or $+-(

**Comment by MarkKoz** [comment]
In that case, follow in its footsteps and also ignore symbol only characters. Probably can merge the number and symbol check together by checking that at least one letter exists. 

I don't know what exactly the regex problem is. If the above does not fix it, then the regex should support symbols too (if it's feasible). If it's too much trouble then I suppose the symbols should be completely blacklisted.
